api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ngo/signup/', views.ngo_signup, name='ngo-signup'),
    path('ngo/logout/', views.ngo_logout, name='ngo-logout'),
    path('customusers/', views.custom_user_list, name='customuser-list'),    
    path('customusers/<int:pk>/', views.custom_user_detail, name='customuser-detail'),
    path('healthworkers/', views.healthworker_list, name='healthworker-list'),
    path('healthworkers/<int:pk>/', views.healthworker_detail, name='healthworker-detail'),
    path('healthworker/signup/', views.healthworker_signup, name='healthworker-signup'),
    path('healthworker/login/', views.healthworker_login, name='healthworker-login'),
    path('ngo/login/', views.ngo_login, name='ngo-login'),
    path('vaccines/', views.vaccine_list, name='vaccine-list'),
    path('vaccines/<str:vaccine_choice>/', views.vaccine_detail, name='vaccine-detail'),
    path('locations/', views.location_list, name='location-list'),
    path('children/', views.child_list, name='child-list'),
    path('children/<int:pk>/', views.child_detail, name='child-detail'),
    path('guardians/', views.guardian_list, name='guardian-list'),
    path('guardians/<int:pk>/', views.guardian_detail, name='guardian-detail'),
    path('guardian/<str:phone_number>/', views.get_guardian_by_phone, name='get_guardian_by_phone'),
    path('immunization-records/<int:child_id>/', views.child_immunization_records, name='immunization_record_detail'),
    path('immunization-records/', views.list_immunization_records, name='immunization_record_list'),
    path('child-vaccine-count/<int:child_id>/', views.child_vaccines_count_api_view, name='child-vaccine-count'),
    path('region_rate/<str:region_name>/',views.immunization_rate,name='immunization-rate'),
    path('regions_rates/',views.all_regions_rates,name='regions_rates')
]

warsan/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Warsan",
        default_version='v1',
        description="Warsan dahsboard and device documentation",
        terms_of_service="https://www.yourapp.com/terms/",
        contact=openapi.Contact(email="warsanakirachix@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),  # Replace with your app's URLs
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("child/",include("child.urls")),
    path("vaccine_records/",include("vaccine_records.urls")),
    #  path("registration/",include("registration.urls"))
    



]

child/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from location.models import Location
from datetime import date


GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
)
STATUS_CHOICES = (
    ('A', 'Active'),
    ('I', 'Inactive'),
)

class Child(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    guardian= models.ForeignKey("Guardian", on_delete=models.SET_NULL,null=True)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='A')
    location = models.ForeignKey(Location, on_delete=models.SET_NULL,null=True)
    phone_number = PhoneNumberField(region='IR')
   
    def save(self, *args, **kwargs):
        if self.guardian:
            self.location = self.guardian.location
            self.phone_number = self.guardian.phone_number
        super().save(*args, **kwargs)


    def  deactivate_child(self,child_detail):
        child = Child.objects.get(pk=child_detail)
        child.status = 'I'
        child.save()
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    def age(self):
        today = date.today()
        age_in_months = (today.year - self.date_of_birth.year) * 12 + (today.month - self.date_of_birth.month)
        return age_in_months 
    class Meta:
        unique_together = ('first_name', 'last_name', 'guardian')
    


from django.db import models
 
from location.models import Location



class Guardian(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL,null=True)
    phone_number = PhoneNumberField(unique=True, region='IR')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='A') 
  

    def  deactivate_guardian(self,guardian_detail):
        # Guardian = Child.objects.get(pk=guardian_detail)
        self.status = 'I'
        self.save()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def register_child(self):
        child = Child.objects.create(
            first_name=self.first_name,
            last_name=self.last_name,
            guardian=self,


            )
        return child

    def get_children(self):
        return self.children.all()
    
        
    def __str__(self):
        return f"{self.first_name} {self.last_name} (Guardian)"

vaccine_records/models.py
from django.db import models
from django.forms import ValidationError
from vaccine.models import Vaccine
from child.models import Child

class Immunization_Record(models.Model):
    child = models.OneToOneField(Child, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=20, choices=[('Taken', 'Taken'), ('Missed', 'Missed')], default='Not administered')
    next_date_of_administration = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'Immunization Record - {self.child.first_name} {self.child.last_name}'



class VaccineAdministration(models.Model):
    record = models.ForeignKey(Immunization_Record, on_delete=models.CASCADE)
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    date_of_administration = models.DateField(null=True, blank=True)

    class Meta:
        unique_together = ('record', 'vaccine')

    def __str__(self):
        return f'Vaccine Administration - {self.vaccine.vaccine_choice} - Date: {self.date_of_administration}'

vaccine_records/forms.py
# forms.py
from django import forms
from vaccine.models import Vaccine
from .models import VaccineAdministration, Immunization_Record
from child.models import Child
class VaccineAdministrationForm(forms.ModelForm):
    class Meta:
        model = VaccineAdministration
        exclude = ['id', 'record']

    date_of_administration = forms.DateField(
        required=True,
        widget=forms.SelectDateWidget(),
        error_messages={'required': 'Please enter a date of administration.'}
    )

class ImmunizationRecordForm(forms.ModelForm):
    child = forms.IntegerField(widget=forms.HiddenInput(), required=False)  # Make the child field hidden and not required

    class Meta:
        model = Immunization_Record
        fields = ['child', 'status', 'next_date_of_administration']

    vaccineadministration_set = forms.inlineformset_factory(
        Immunization_Record,
        VaccineAdministration,
        form=VaccineAdministrationForm,
        extra=1,
        can_delete=False,
        can_order=False
    )

templates/records/create_immunization_record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <style>
        body{
            font-family: 'Kumbh Sans', sans-serif;

        }
    </style>
    <h2> {{ child.first_name }} {{ child.last_name }}</h2>

<form method="POST" action="{% url 'immunization_detail' child_data.child.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload Immunization</button>
</form>
</body>
</html>

templates/records/immunization_record_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Immunization Record Detail</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 20px;
            padding: 70px;

        }

        h1 {
            background-color: #3498db;
            color: #fff;
            padding: 20px;
            text-align: center;
            font-size: 28px; 
        }

        .container {
            max-width: 800px;
            margin: 40px auto;
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            border-radius: 5px;
            font-family: 'Kumbh Sans', sans-serif;

        }

        p {
            margin: 10px 0;
            font-size: 18px;
        }

        .vaccine-list {
            margin-top: 20px; 
        }

        .vaccine-item {
            padding: 8px 12px; /* Increased padding */
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 8px 0;
            background-color: #f5f5f5;
            font-size: 18px;
            display: inline-block;
            color: #333;
        }

        strong {
            font-weight: bold;
        }

        .floating-button {
            position: fixed;
            bottom: 40px;
            right: 40px;
            background-color: #3498db;
            color: #fff;
            border: none;
            border-radius: 50%;
            width: 60px;
            height: 60px;
            font-size: 24px;
            text-align: center;
            line-height: 60px;
            cursor: pointer;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
            text-decoration: none; 
        }

        .floating-button:hover {
            background-color: #258cd1;
        }
        .large-arrow {
            font-size: 36px; 
        }
    </style>
</head>
<body>
    <a href="{% url 'guardian_detail' guardian_id=immunization_record.child.guardian.id %}" class="back-arrow large-arrow">&#8592;</a>

    <h1>Immunization Record Detail</h1>
    <div class="container">
        {% if immunization_record %}
            <p><strong>Child:</strong> {{ immunization_record.child }}</p>
            <p><strong>Status:</strong> {{ immunization_record.status }}</p>
            <p><strong>Next Date of Administration (Due Date):</strong> {{ immunization_record.next_date_of_administration }}</p>
          
            <div class="vaccine-list">
                <h3><strong>Vaccines:</strong></h3>
                <ul>
                    {% for vaccine in immunization_record.vaccine.all %}
                        <li class="vaccine-item">{{ vaccine.get_vaccine_choice_display }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <p>No immunization record found for this child.</p>
            <a href="{% url 'create_immunization_record' child_id=immunization_record.child.id %}">Start giving vaccines</a>
        {% endif %}
    </div>
    
    <a href="{% url 'update_immunization_record' record_id=immunization_record.id %}" class="floating-button">+</a></body>
</html>

templates/records/update_immunization_record.html
<!-- update_immunization_record.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Immunization Record</title>
    <style>
        body {
            font-family: 'Kumbh Sans', sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .form-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            width: 500px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
            color: #1175D2;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            /* font-weight: bold; */
        }

        input[type="text"],
        input[type="date"],
        select {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button[type="submit"] {
            background-color:#1175D2;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color:#81b3e1;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="form-container">
            <h2>Update Immunization Record</h2>

            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_vaccine">Vaccine:</label>
                    {{ form.vaccine }}
                </div>
                <div class="form-group">
                    <label for="id_date_of_administration">Date of Administration:</label>
                    {{ form.date_of_administration }}
                </div>
                <div class="form-group">
                    <label for="id_next_date_of_administration">Next Date of Administration:</label>
                    {{ form.next_date_of_administration }}
                </div>
                <div class="form-group">
                    <label for="id_status">Status:</label>
                    {{ form.status }}
                </div>
                <button type="submit">Upload Immunization</button>
            </form>
        </div>
    </div>
</body>
</html>