api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ngo/signup/', views.ngo_signup, name='ngo-signup'),
    path('ngo/logout/', views.ngo_logout, name='ngo-logout'),
    path('customusers/', views.custom_user_list, name='customuser-list'),    
    path('customusers/<int:pk>/', views.custom_user_detail, name='customuser-detail'),
    path('healthworkers/', views.healthworker_list, name='healthworker-list'),
    path('healthworkers/<int:pk>/', views.healthworker_detail, name='healthworker-detail'),
    path('healthworker/signup/', views.healthworker_signup, name='healthworker-signup'),
    path('healthworker/login/', views.healthworker_login, name='healthworker-login'),
    path('ngo/login/', views.ngo_login, name='ngo-login'),
    path('vaccines/', views.vaccine_list, name='vaccine-list'),
    path('vaccines/<str:vaccine_choice>/', views.vaccine_detail, name='vaccine-detail'),
    path('locations/', views.location_list, name='location-list'),
    path('children/', views.child_list, name='child-list'),
    path('children/<int:pk>/', views.child_detail, name='child-detail'),
    path('guardians/', views.guardian_list, name='guardian-list'),
    path('guardians/<int:pk>/', views.guardian_detail, name='guardian-detail'),
    path('guardian/<str:phone_number>/', views.get_guardian_by_phone, name='get_guardian_by_phone'),
    path('immunization-records/<int:child_id>/', views.child_immunization_records, name='immunization_record_detail'),
    path('immunization-records/', views.list_immunization_records, name='immunization_record_list'),
    path('child-vaccine-count/<int:child_id>/', views.child_vaccines_count_api_view, name='child-vaccine-count'),
    path('region_rate/<str:region_name>/',views.immunization_rate,name='immunization-rate'),
    path('regions_rates/',views.all_regions_rates,name='regions_rates')
]

warsan/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Warsan",
        default_version='v1',
        description="Warsan dahsboard and device documentation",
        terms_of_service="https://www.yourapp.com/terms/",
        contact=openapi.Contact(email="warsanakirachix@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),  # Replace with your app's URLs
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("child/",include("child.urls")),
    path("vaccine_records/",include("vaccine_records.urls")),
    #  path("registration/",include("registration.urls"))
    



]

vaccine_records/models.py
from django.db import models
from django.forms import ValidationError
from vaccine.models import Vaccine
from child.models import Child

class Immunization_Record(models.Model):
    child = models.OneToOneField(Child, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=20, choices=[('Taken', 'Taken'), ('Missed', 'Missed')], default='Not administered')
    next_date_of_administration = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'Immunization Record - {self.child.first_name} {self.child.last_name}'



class VaccineAdministration(models.Model):
    record = models.ForeignKey(Immunization_Record, on_delete=models.CASCADE)
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    date_of_administration = models.DateField(null=True, blank=True)

    class Meta:
        unique_together = ('record', 'vaccine')

    def __str__(self):
        return f'Vaccine Administration - {self.vaccine.vaccine_choice} - Date: {self.date_of_administration}'

templates/create_immunization_record.html
<!DOCTYPE html>
<html>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">

<head>
    <title>Create Immunization Record</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            height: 100vh;
            font-family: Arial, sans-serif;
            background-color: #F4F4F4;
        }

        h2 {
            color: #1175D2;

        }

        form {
            width: 100%;
            max-width: 600px;
            padding: 10px;
            margin: 20px;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        form button[type="submit"] {
            display: block;
            margin: 20px auto;
            padding: 10px 20px;
            background-color: #1175D2;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .vaccine-form {
            display: flex;
            flex-direction: column;
        }

        .vaccine-form label {
            font-weight: 200;
            font-size: 20px;
            margin: 10px 0;
        }

        .vaccine-form input[type="date"],
        .vaccine-form select {
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <form method="post">
        <h2>Add Immunization Record</h2>
        {% csrf_token %}
        <div class="vaccine-form">
            {{ form.as_p }}
            {{ form.vaccineadministration_set.management_form }}
            {% for formset_form in form.vaccineadministration_set %}
                {{ formset_form.as_table }}
            {% endfor %}
        </div>
        <button type="submit">Save</button>
    </form>
</body>
</html>

templates/healthworker_login.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>


</body>
</html> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            border-radius: 5px;
            width: 300px;
        }

        h1 {
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        button[type="submit"] {
            background-color: #3498db;
            color: #fff;
            border: none;
            border-radius: 3px;
            padding: 10px 20px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #258cd1;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h1>Login</h1>
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

templates/immunization_detail.html
<!DOCTYPE html>
<html>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">

<head>
    <title>Immunization Details</title>
    <style>
        /* Common styles */
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            font-family: Arial, sans-serif;
        }

        h2 {
            color: #1175D2;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            margin-top: 20px;
            width: 100%;
            max-width: 600px; /* Adjust the maximum width as needed */
        }

        table, th, td {
            border: 1px solid #ccc;
        }

        th, td {
            padding: 8px;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        ul li {
            margin-bottom: 10px;
        }

        a {
            color: #1175D2;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        /* Responsive styles for small screens */
        @media (max-width: 768px) {
            h2 {
                font-size: 24px;
            }

            table {
                max-width: 90%; /* Adjust the maximum width for smaller screens */
            }

            th, td {
                padding: 6px;
            }

            ul li {
                margin-bottom: 6px;
                font-size: 14px;
            }

            a {
                font-size: 14px;
            }
        }

        /* Responsive styles for iPads */
        @media (min-width: 768px) and (max-width: 1024px) {
            h2 {
                font-size: 32px;
            }

            table {
                max-width: 80%;
                font-size: 30px;
            }

            th, td {
                padding: 10px;
            }

            ul li {
                margin-bottom: 8px;
                font-size: 16px;
            }

            a {
                font-size: 16px;
            }

        }
    </style>
</head>
<body>
    <h2>{{ record.child }}</h2>
    <table>
        <tr>
            <th>Status</th>
            <td>{{ record.status }}</td>
        </tr>
        <tr>
            <th>Next Date of Administration</th>
            <td>{{ record.next_date_of_administration }}</td>
        </tr>
    </table>
    <h3>Vaccine Administrations:</h3>
    <ul>
        {% for administration in record.vaccineadministration_set.all %}
            <li>{{ administration.vaccine }} (Administered on: {{ administration.date_of_administration }})</li>
        {% endfor %}
    </ul>
    <a href="{% url 'guardian_detail' guardian_id=record.child.guardian.id %}">Back to Guardian Details</a>
</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Our Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            display: flex; /* Use flexbox to center content */
            justify-content: center; /* Horizontally center content */
            align-items: center; /* Vertically center content */
            height: 100vh; /* Full viewport height */
            margin: 0;
        }

        .container {
            max-width: 600px;
            padding: 40px;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            font-family: 'Kumbh sans', sans-serif;
        }

        h1 {
            color: #3498db;
        }

        p {
            font-size: 18px;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            background-color: #3498db;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
        }

        .btn:hover {
            background-color: #258cd1;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to Rajo Device</h1>
        <p>Dear Community Health Volunteer,</p>
        <p>Thank you for your dedication to improving healthcare in our community.</p>
        <p style="color: rgb(253, 9, 253);">Together, we can make a difference in the lives of the children and families we serve.</p>
        <a href="/child/guardian/retrieve" class="btn">Get Started</a>
    </div>
</body>
</html>